# Pandas

Es una libreria open source para análisis y procesamiento de datos, que demas facilita la creación de estructuras de datos de una forma muy sencilla.
Aprenderemos a leer archivos y transformarlos en estructuras de datos que nos van a facilitar mucho la vida a la hora de analizarlos.

## Archivos CSV (Local y web)

** CSV **: Comma separated values

In [2]:
import pandas as pd

In [3]:
raw_data = {
    'first_mane': ['John','Carmen','Camilla','Vladimir','Miguel'],
    'last_mane': ['Porras','Mendiola','Hurtado','Ramirez','Casana'],
    'age': [42, 52, 36, 24, 73],
    'presTestScore': [4, 24, 61, ".", "."],
    'postTestScore': ["25,000", "94,000", 27, 62, 70]
    
}
df = pd.DataFrame(raw_data)
df

   age first_mane last_mane postTestScore presTestScore
0   42       John    Porras        25,000             4
1   52     Carmen  Mendiola        94,000            24
2   36    Camilla   Hurtado            27            61
3   24   Vladimir   Ramirez            62             .
4   73     Miguel    Casana            70             .

### Guardar nuestro datos como csv

In [5]:
df.to_csv('EjemploPadas.csv')

### Leer un archivo local CSV

In [8]:
datos = pd.read_csv('EjemploPadas.csv')
datos

   Unnamed: 0  age first_mane last_mane postTestScore presTestScore
0           0   42       John    Porras        25,000             4
1           1   52     Carmen  Mendiola        94,000            24
2           2   36    Camilla   Hurtado            27            61
3           3   24   Vladimir   Ramirez            62             .
4           4   73     Miguel    Casana            70             .

### Leer un CSV sin barra de titulos (Headers)

In [9]:
datos = pd.read_csv('EjemploPadas.csv', header=None)
datos

     0    1           2          3              4              5
0  NaN  age  first_mane  last_mane  postTestScore  presTestScore
1  0.0   42        John     Porras         25,000              4
2  1.0   52      Carmen   Mendiola         94,000             24
3  2.0   36     Camilla    Hurtado             27             61
4  3.0   24    Vladimir    Ramirez             62              .
5  4.0   73      Miguel     Casana             70              .

In [10]:
datos = pd.read_csv('EjemploPadas.csv', header=None, skiprows = 1)
datos

   0   1         2         3       4   5
0  0  42      John    Porras  25,000   4
1  1  52    Carmen  Mendiola  94,000  24
2  2  36   Camilla   Hurtado      27  61
3  3  24  Vladimir   Ramirez      62   .
4  4  73    Miguel    Casana      70   .

In [13]:
datos = pd.read_csv('EjemploPadas.csv', index_col='UID', skiprows = 1, names=['UID','Nombre','Apellido','Edad','Puntaje 1','Puntaje 2'])
datos

     Nombre  Apellido      Edad Puntaje 1 Puntaje 2
UID
0        42      John    Porras    25,000         4
1        52    Carmen  Mendiola    94,000        24
2        36   Camilla   Hurtado        27        61
3        24  Vladimir   Ramirez        62         .
4        73    Miguel    Casana        70         .

### Leer CSV desde la web

In [15]:
datos_web = pd.read_csv('http://winterolympicsmedals.com/medals.csv')
datos_web.head()

,Year,City,Sport,Discipline,NOC,Event,Event gender,Medal
0,1924,Chamonix,Skating,Figure skating,AUT,individual,M,Silver
1,1924,Chamonix,Skating,Figure skating,AUT,individual,W,Gold
2,1924,Chamonix,Skating,Figure skating,AUT,pairs,X,Gold
3,1924,Chamonix,Bobsleigh,Bobsleigh,BEL,four-man,M,Bronze
4,1924,Chamonix,Ice Hockey,Ice Hockey,CAN,ice hockey,M,Gold

## Leer archivos Excel

In [20]:
datos_excel = pd.read_excel(open('frutas.xlsx', 'rb'), sheetname='Hoja1')
datos_excel.head()

   fruit_labe fruit_name fruit_subtype  mass  width  height  color_score
0           1    manzana   desconocido   192    8.4     7.3         0.55
1           1    manzana   desconocido   180    8.0     6.8         0.59
2           1    manzana   desconocido   176    7.4     7.2         0.60
3           2  mandarina     mandarina    86    6.2     4.7         0.80
4           2  mandarina     mandarina    84    6.0     4.6         0.79

In [21]:
datos_excel.columns

Index(['fruit_labe', 'fruit_name', 'fruit_subtype', 'mass', 'width', 'height',
       'color_score'],
      dtype='object')

In [22]:
datos_excel.columns[3]

'mass'

In [24]:
#vamos a imprimir todos las masas de las frutas
for i in datos_excel.index:
    print("Peso de la fruta {} = {}".format(i, datos_excel['mass'][i]))

Peso de la fruta 0 = 192
Peso de la fruta 1 = 180
Peso de la fruta 2 = 176
Peso de la fruta 3 = 86
Peso de la fruta 4 = 84