## Creando una lista aleatoria

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

creando una lista de 100 unidades
pd.concat([data, dummy_sex], axis=1)

In [105]:
data = pd.DataFrame(columns=('plato', 'personal', 'tiempo', 'precio', 'semana'))

In [106]:
def crearLista(n, a, b):
    x = []
    for i in range(n):
        x.append(np.random.randint(a,b))
    return x

In [107]:
data["plato"]    = crearLista(100, 10, 100)
data["personal"] = crearLista(100, 1, 5)
data["tiempo"]   = crearLista(100, 3, 10)
data["precio"]   = crearLista(100, 50, 100)
data["semana"]   = crearLista(100, 1, 7)

In [108]:
data.head()

   plato  personal  tiempo  precio  semana
0     11         4       6      70       1
1     99         1       9      55       2
2     77         2       3      73       2
3     59         3       8      68       2
4     17         3       6      90       5

In [149]:
np.savetxt("../datasets/practicas/don_panza.csv",   # Archivo de salida
           data,        # Trasponemos los datos se usa T
           fmt="%d",       # Usamos números enteros
           delimiter=","
           #newline="\n"
           )

In [177]:
encabezado = pd.read_csv("../datasets/practicas/encabezado.csv")

In [180]:
encabezado.tolist()

AttributeError: 'DataFrame' object has no attribute 'tolist'

In [181]:
encabezado.head()

Empty DataFrame
Columns: [plato,  personal,  tiempo,  precio,  semana]
Index: []

In [175]:
res = pd.read_csv("../datasets/practicas/don_panza.csv", 
                  index_col=0, skip_blank_lines=True, names=['plato','personal','tiempo','precio', 'semana'])

In [173]:
res.head()

   plato   personal   tiempo   precio   semana
0     11          4        6       70        1
1     99          1        9       55        2
2     77          2        3       73        2
3     59          3        8       68        2
4     17          3        6       90        5

In [164]:
datos = pd.concat(res, sep=';', index_col=0, skip_blank_lines=True, names=encabezado.values.tolist())

TypeError: concat() got an unexpected keyword argument 'sep'

In [163]:
datos.head()

   personal  precio  semana  tiempo    1    11    4    6    70 plato
0       NaN     NaN     NaN     NaN  2.0  99.0  1.0  9.0  55.0   NaN
1       NaN     NaN     NaN     NaN  2.0  77.0  2.0  3.0  73.0   NaN
2       NaN     NaN     NaN     NaN  2.0  59.0  3.0  8.0  68.0   NaN
3       NaN     NaN     NaN     NaN  5.0  17.0  3.0  6.0  90.0   NaN
4       NaN     NaN     NaN     NaN  5.0  15.0  1.0  3.0  79.0   NaN